from __future__ import annotations

from app.core.config import settings
from app.schemas.attendance import (
    LivenessVerificationRequest,
    LivenessVerificationResponse,
    ModelSummary,
)


class LiveVerificationPipeline:
    def __init__(
        self,
        enrollment_repository,
        face_recognition_service,
        liveness_service,
        anti_spoof_service,
    ) -> None:
        self.enrollment_repository = enrollment_repository
        self.face_recognition_service = face_recognition_service
        self.liveness_service = liveness_service
        self.anti_spoof_service = anti_spoof_service

    def verify(
        self, payload: LivenessVerificationRequest
    ) -> LivenessVerificationResponse:
        enrolled_profile = self.enrollment_repository.get_profile(payload.personId)
        capture_result = self.face_recognition_service.build_capture_embedding(
            track_key=f"live::{payload.personId}",
            source_capture_ids=payload.captureImages,
            enrolled_profile=enrolled_profile,
            low_confidence=False,
        )

        if (
            settings.execution_mode == "simulated"
            and payload.simulationHints
            and payload.simulationHints.identityConfidence is not None
        ):
            identity_confidence = round(payload.simulationHints.identityConfidence, 2)
        elif enrolled_profile is None:
            identity_confidence = 0.0
        elif not self.face_recognition_service.is_profile_compatible(enrolled_profile):
            identity_confidence = 0.0
        else:
            identity_confidence = self.face_recognition_service.compare_embedding_to_profile(
                embedding=capture_result.embedding,
                profile=enrolled_profile,
            )

        blink_detected, head_turn_detected, active_liveness_score, liveness_notes = (
            self.liveness_service.evaluate(payload)
        )
        passive_spoof_score, anti_spoof_notes = self.anti_spoof_service.evaluate(payload)

        requires_blink = "blink" in payload.expectedMovements
        requires_head_movement = any(
            movement in {"turn_left", "turn_right", "look_up", "look_down"}
            for movement in payload.expectedMovements
        )
        requires_active_liveness = requires_blink or requires_head_movement

        accepted = (
            identity_confidence >= settings.recognition_threshold
            and passive_spoof_score >= settings.passive_spoof_threshold
            and (
                not requires_active_liveness
                or active_liveness_score >= settings.active_liveness_threshold
            )
            and (blink_detected or not requires_blink)
            and (head_turn_detected or not requires_head_movement)
        )

        notes = [
            "Live verification combined identity matching, active liveness, and passive anti-spoof scoring.",
        ]
        notes.extend(capture_result.warnings)
        notes.extend(liveness_notes)
        notes.extend(anti_spoof_notes)
        if enrolled_profile is None:
            notes.append("No enrolled profile was found for the requested person ID.")
        elif not self.face_recognition_service.is_profile_compatible(enrolled_profile):
            notes.append(
                "The enrolled profile was created with an older or different embedding model. Re-enrollment is required before live verification can pass."
            )
        if passive_spoof_score < settings.passive_spoof_threshold:
            notes.append("Passive anti-spoof score is below the safety threshold.")
        if (
            requires_active_liveness
            and active_liveness_score < settings.active_liveness_threshold
        ):
            notes.append("Active liveness score is below the safety threshold.")
        if settings.execution_mode == "simulated":
            notes.append(
                "Scores are currently generated by the service simulator until the production model weights are configured."
            )
        else:
            notes.append(
                "Verification used InsightFace embeddings, MediaPipe landmarks, and passive image-signal scoring."
            )

        recommended_action = "allow"
        if (
            not accepted
            and enrolled_profile is not None
            and not self.face_recognition_service.is_profile_compatible(enrolled_profile)
        ):
            recommended_action = "manual-review"
        elif not accepted and passive_spoof_score < settings.passive_spoof_threshold:
            recommended_action = "manual-review"
        elif not accepted:
            recommended_action = "retry-capture"

        return LivenessVerificationResponse(
            personId=payload.personId,
            accepted=accepted,
            identityConfidence=round(identity_confidence, 2),
            activeLivenessScore=round(active_liveness_score, 2),
            passiveSpoofScore=round(passive_spoof_score, 2),
            blinkDetected=blink_detected,
            headMovementDetected=head_turn_detected,
            recommendedAction=recommended_action,
            modelSummary=self._build_model_summary(),
            notes=notes,
        )

    def _build_model_summary(self) -> ModelSummary:
        return ModelSummary(
            executionMode=settings.execution_mode,
            faceDetection=settings.face_detection_model,
            faceTracking=settings.face_tracking_model,
            faceRecognition=settings.face_recognition_model,
            liveness=settings.liveness_model,
            antiSpoof=settings.anti_spoof_model,
        )
